[container]
image = "jekyll/jekyll"
os_flavor = "alpine"

work_dir = "/usr/src/app"

mounts = [
    ".:/usr/src/app:ro"
]
ports = [
    "4000:4000"
]


# jekyll serve -d /_site --watch --force_polling -H 0.0.0.0 -P 4000
